version: '3.3'

services:
  backend-blue:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: '*'
        DJANGO_SECRET_KEY: 'ek3u^o%t$ei@d43j_z&(8bme&lp24cbf^qr(6&(b=9vx-(l9rv'
        DJANGO_CORS_ORIGIN_WHITELIST: >-
                                    http://ec2-13-125-77-159.ap-northeast-2.compute.amazonaws.com
                                    http://13.125.77.159
                                    http://13.125.77.159:8080
                                    http://13.125.77.159:8082
                                    http://flglance.net
                                    http://flglance.net:8080
                                    http://flglance.net:8082
                                    https://flglance.net
                                    https://flglance.net:8080
                                    https://flglance.net:8082
        BACKEND_ADMIN: '36JV9e3gtgrLYJTD'
        RDS_HOSTNAME: 'flglancedbinstance.cnccbx1rihhz.ap-northeast-2.rds.amazonaws.com'
        RDS_PORT: 5432
        RDS_DB_NAME: 'postgres'
        RDS_USERNAME: 'postgres'
        RDS_PASSWORD: '8*7Ld.?{<vw>`L'
        S3_ACCESS_KEY_ID: 'AKIA3Q7SB7PEC5SQGO4E'
        S3_SECRET_ACCESS_KEY: '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'
        S3_BUCKET_NAME: 'flglance-storage-bucket'
        DEBUG: 'False'
        EMAIL_HOST_USER: 'joseph@mail.flglance.net'
        EMAIL_HOST_PASSWORD: '8b3a666a798dd146141ecd32a583e324-e49cc42c-1d04dd45'
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend-blue:
    build:
      context: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - build_folder:/frontend/build
  nginx-blue:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - build_folder:/var/www/frontend
    depends_on:
      - backend-blue
      - frontend-blue
volumes:
  build_folder:
