version: '3'

services:
  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: ec2-13-124-154-216.ap-northeast-2.compute.amazonaws.com, api
        SECRET_KEY: ek3u^o%t$ei@d43j_z&(8bme&lp24cbf^qr(6&(b=9vx-(l9rv
        DJANGO_CORS_ORIGIN_WHITELIST: http://ec2-13-124-154-216.ap-northeast-2.compute.amazonaws.com
        BACKEND_ADMIN: 36JV9e3gtgrLYJTD
        RDS_HOSTNAME: flglancedbinstance.cnccbx1rihhz.ap-northeast-2.rds.amazonaws.com
        RDS_PORT: 5432
        RDS_DB_NAME: flglancedbinstance
        RDS_USERNAME: postgres
        RDS_PASSWORD: 8*7Ld.?{<vw>`L
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_API: http://ec2-13-124-154-216.ap-northeast-2.compute.amazonaws.com:8000
    volumes:
      - build_folder:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  build_folder: