version: '3.3'

services:
  backend-green:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: >-
                            ec2-13-125-77-159.ap-northeast-2.compute.amazonaws.com
                            172.31.44.236
                            ip-172-31-44-236.ap-northeast-2.compute.internal
                            13.125.77.159
                            flglance.net
                            1.250.241.55
                            localhost
                            api
        DJANGO_SECRET_KEY: 'ek3u^o%t$ei@d43j_z&(8bme&lp24cbf^qr(6&(b=9vx-(l9rv'
        DJANGO_CORS_ORIGIN_WHITELIST: >-
                                    http://ec2-13-125-77-159.ap-northeast-2.compute.amazonaws.com
                                    http://13.125.77.159
                                    http://13.125.77.159:8080
                                    http://13.125.77.159:8082
                                    http://flglance.net
                                    https://flglance.net
        BACKEND_ADMIN: '36JV9e3gtgrLYJTD'
        RDS_HOSTNAME: 'flglancedbinstance.cnccbx1rihhz.ap-northeast-2.rds.amazonaws.com'
        RDS_PORT: 5432
        RDS_DB_NAME: 'postgres'
        RDS_USERNAME: 'postgres'
        RDS_PASSWORD: '8*7Ld.?{<vw>`L'
        S3_ACCESS_KEY_ID: 'AKIA3Q7SB7PEC5SQGO4E'
        S3_SECRET_ACCESS_KEY: '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'
        S3_BUCKET_NAME: 'flglance-storage-bucket'
        DEBUG: 'False'
        EMAIL_HOST_USER: 'joseph@mail.flglance.net'
        EMAIL_HOST_PASSWORD: '8b3a666a798dd146141ecd32a583e324-e49cc42c-1d04dd45'
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8001:8000"
  frontend-green:
    build:
      context: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - build_folder:/frontend/build
  nginx-green:
    image: nginx:latest
    ports:
      - "8082:8080"
      - "8083:8081"
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - build_folder:/var/www/frontend
    depends_on:
      - backend-green
      - frontend-green
volumes:
  build_folder:
