# Generated by Django 3.1.5 on 2021-01-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20210121_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contributor',
            new_name='participants',
        ),
    ]
