# Generated by Django 3.1.5 on 2021-02-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
